version: '3.8'

services:
  instagram-photos:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
